import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * Writes the compiled ABI into the web application as a typed constant.
 *
 * Generated rather than hand-maintained, so the ABI the application encodes
 * with can never drift from the contract that was actually deployed. The output
 * is committed, so the app builds without needing the Solidity toolchain.
 */
const ARTIFACT = path.join(
  import.meta.dirname,
  "..",
  "artifacts",
  "src",
  "ProofChainRegistry.sol",
  "ProofChainRegistry.json",
);

const OUTPUT = path.join(
  import.meta.dirname,
  "..",
  "..",
  "src",
  "lib",
  "blockchain",
  "abi.ts",
);

async function main() {
  const artifact = JSON.parse(await readFile(ARTIFACT, "utf8")) as {
    abi: unknown[];
  };

  const body = `// Generated by contracts/scripts/export-abi.ts — do not edit by hand.
// Regenerate with: cd contracts && npm run compile && npm run export-abi

export const PROOF_CHAIN_REGISTRY_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  await mkdir(path.dirname(OUTPUT), { recursive: true });
  await writeFile(OUTPUT, body);
  console.log(`Wrote ${path.relative(process.cwd(), OUTPUT)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
